baseURL = 'https://gerolds.github.io/textbook/'
languageCode = 'en'
title = 'Textbook'
theme = 'monochrome'
copyright = '© Gerold Schneider'
disablePathToLower = true
enableRobotsTXT = true
enableGitInfo = false

[outputs]
  section = ['HTML', 'RSS', 'pdf-manifest']

[outputFormats.pdf-manifest]
  mediaType = 'application/json'
  baseName = 'pdf-manifest'
  isPlainText = true
  notAlternative = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[markup.highlight]
  style = 'monokai'

[params]
  BookTheme = 'auto'
  BookSection = 'posts'
  BookSearch = true
  BookComments = false
  BookDateFormat = 'Jan 2, 2006'
  BookPortableLinks = 'warning'
  enable_toc = true
  toc_position = 'right'
  enable_collapsible_toc = false

[[menu.after]]
  name = 'Essays'
  pageRef = '/posts/'
  weight = 1

[[menu.after]]
  name = 'About'
  pageRef = '/about/'
  weight = 2

[[menu.after]]
  name = 'Tags'
  pageRef = '/tags/'
  weight = 3

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
